CREATE TABLE HEWAN(
	IdSDAHayati VARCHAR(30),
	NamaSDA VARCHAR(30),
	NamaLatin VARCHAR(30),
	Habitat VARCHAR(50),
	KingdomAnimalia VARCHAR(30),
	CONSTRAINT PK_HEWAN_IdSDAHayati PRIMARY KEY (IdSDAHayati)
)

CREATE TABLE TUMBUHAN(
	IdSDAHayati VARCHAR(30),
	NamaSDA VARCHAR(30),
	NamaLatin VARCHAR(30),
	Habitat VARCHAR(50),
	KingdomPlantae VARCHAR(30),
	CONSTRAINT PK_TUMBUHAN_IdSDAHayati PRIMARY KEY (IdSDAHayati)
)

CREATE TABLE MIGAS(
	IdSDANonHayati VARCHAR(30),
	NamaSDA VARCHAR(30),
	LetakSDA VARCHAR(50),
	UnsurKimia VARCHAR(30),
	JmlPersediaan INT,
	BatuanResevoir VARCHAR(30),
	CONSTRAINT PK_MIGAS_IdSDANonHayati PRIMARY KEY (IdSDANonHayati)
)

CREATE TABLE LOGAM(
	IdSDANonHayati VARCHAR(30),
	NamaSDA VARCHAR(30),
	LetakSDA VARCHAR(50),
	UnsurKimia VARCHAR(30),
	JmlPersediaan INT,
	KemurnianLogam VARCHAR(30),
	CONSTRAINT PK_LOGAM_IdSDANonHayati PRIMARY KEY (IdSDANonHayati)
)

CREATE TABLE MEMILIKI_HEWAN(
	KdLaut VARCHAR(20),
	IdHayati VARCHAR(30),
	CONSTRAINT FK_MEMILIKIHEW_KdLaut FOREIGN KEY (KdLaut) REFERENCES LAUT(Kode),
	CONSTRAINT FK_MEMILIKIHEW_IdHayati FOREIGN KEY (IdHayati) REFERENCES HEWAN(IdSDAHayati),
	CONSTRAINT PK_MEMILIKIHEW PRIMARY KEY (KdLaut, IdHayati)
)

CREATE TABLE MEMILIKI_TUMBUHAN(
	KdLaut VARCHAR(20),
	IdHayati VARCHAR(30),
	CONSTRAINT FK_MEMILIKITUM_KdLaut FOREIGN KEY (KdLaut) REFERENCES LAUT(Kode),
	CONSTRAINT FK_MEMILIKITUM_IdHayati FOREIGN KEY (IdHayati) REFERENCES TUMBUHAN(IdSDAHayati),
	CONSTRAINT PK_MEMILIKITUM PRIMARY KEY (KdLaut, IdHayati)
)

CREATE TABLE TERDAPAT_MIGAS(
	KdLaut VARCHAR(20),
	IdNonHayati VARCHAR(30),
	CONSTRAINT FK_TERDAPATMIG_KdLaut FOREIGN KEY (KdLaut) REFERENCES LAUT(Kode),
	CONSTRAINT FK_TERDAPATMIG_IdNonHayati FOREIGN KEY (IdNonHayati) REFERENCES MIGAS(IdSDANonHayati),
	CONSTRAINT PK_TERDAPATMIG PRIMARY KEY (KdLaut, IdNonHayati)
)

CREATE TABLE TERDAPAT_LOGAM(
	KdLaut VARCHAR(20),
	IdNonHayati VARCHAR(30),
	CONSTRAINT FK_TERDAPATLOG_KdLaut FOREIGN KEY (KdLaut) REFERENCES LAUT(Kode),
	CONSTRAINT FK_TERDAPATLOG_IdNonHayati FOREIGN KEY (IdNonHayati) REFERENCES LOGAM(IdSDANonHayati),
	CONSTRAINT PK_TERDAPATLOG PRIMARY KEY (KdLaut, IdNonHayati)
)