CREATE TABLE HEWAN(
	IdSDAHayati VARCHAR(20) NOT NULL,
	NamaSDA VARCHAR(30),
	NamaLatin VARCHAR(30),
	Habitat VARCHAR(50),
	KingdomAnimalia VARCHAR(30),
	PRIMARY KEY (IdSDAHayati)
)

CREATE TABLE TUMBUHAN(
	IdSDAHayati VARCHAR(20) NOT NULL,
	NamaSDA VARCHAR(30),
	NamaLatin VARCHAR(30),
	Habitat VARCHAR(50),
	KingdomPlantae VARCHAR(30),
	PRIMARY KEY (IdSDAHayati)
)

CREATE TABLE MIGAS(
	IdSDANonHayati VARCHAR(20) NOT NULL,
	NamaSDA VARCHAR(30),
	LetakSDA VARCHAR(50),
	UnsurKimia NVARCHAR(30),
	JmlPersediaan FLOAT,
	BatuanResevoir VARCHAR(30),
	PRIMARY KEY (IdSDANonHayati)
)

CREATE TABLE LOGAM(
	IdSDANonHayati VARCHAR(20),
	NamaSDA VARCHAR(30),
	LetakSDA VARCHAR(50),
	UnsurKimia NVARCHAR(30),
	JmlPersediaan FLOAT,
	KemurnianLogam VARCHAR(30),
	PRIMARY KEY (IdSDANonHayati)
)

CREATE TABLE MEMILIKI(
	KdLaut VARCHAR(20),
	IdHayati VARCHAR(20),
	CONSTRAINT FK_MEMILIKI_Laut FOREIGN KEY (KdLaut) REFERENCES LAUT(Kode),
	CONSTRAINT FK_MEMILIKI_hewanHayati FOREIGN KEY (IdHayati) REFERENCES HEWAN(IdSDAHayati),
	CONSTRAINT FK_MEMILIKI_tumbuhanHayati FOREIGN KEY (IdHayati) REFERENCES TUMBUHAN(IdSDAHayati),
	PRIMARY KEY (KdLaut, IdHayati)
)

CREATE TABLE TERDAPAT_MIGAS(
	KdLaut VARCHAR(20),
	IdNonHayati VARCHAR(20),
	CONSTRAINT FK_TERDAPAT_Laut FOREIGN KEY (KdLaut) REFERENCES LAUT(Kode),
	CONSTRAINT FK_TERDAPAT_migasNonHayati FOREIGN KEY (IdNonHayati) REFERENCES MIGAS(IdSDANonHayati),
	CONSTRAINT FK_TERDAPAT_logamNonHayati FOREIGN KEY (IdNonHayati) REFERENCES LOGAM(IdSDANonHayati),
	PRIMARY KEY (KdLaut, IdNonHayati)
)