
CREATE TABLE MIGAS(
	IdSDANonHayati VARCHAR(30),
	NamaSDA VARCHAR(30),
	LetakSDA VARCHAR(50),
	UnsurKimia VARCHAR(100), --30 -> 100
	JmlPersediaan INT,
	HargaMigas VARCHAR(30),
	CONSTRAINT PK_MIGAS_IdSDANonHayati PRIMARY KEY (IdSDANonHayati)
)

CREATE TABLE LOGAM(
	IdSDANonHayati VARCHAR(30),
	NamaSDA VARCHAR(30),
	LetakSDA VARCHAR(50),
	UnsurKimia VARCHAR(30),
	JmlPersediaan INT,
	HargaLogam VARCHAR(30),
	CONSTRAINT PK_LOGAM_IdSDANonHayati PRIMARY KEY (IdSDANonHayati)
)

INSERT INTO TUMBUHAN
VALUES('PSTA-001','Gracilaria','Gracilaria','Perairan tropik','Protista')
INSERT INTO TUMBUHAN
VALUES('PSTA-002','Rumput Laut','Eucheuma','Perairan tropik','Protista')
INSERT INTO TUMBUHAN
VALUES('MNRA-001','Ganggang Hijau-Biru','Cyanophyta','Perairan pesisir','Monera')
INSERT INTO TUMBUHAN
VALUES('PSTA-003','Alga Hijau','Chlorophyta','Perairan pesisir','Protista')
INSERT INTO TUMBUHAN
VALUES('PSTA-004','Alga Coklat','Phaeophyceae','Perairan dingin','Protista')

INSERT INTO HEWAN
VALUES('IKNP-312','Ikan Tongkol','Euthynnus Affinis','Perairan pesisir','Animalia')
INSERT INTO HEWAN
VALUES('IKNP-238','Ikan Bandeng','Chanos Chanos','Perairan pesisir','Animalia')
INSERT INTO HEWAN
VALUES('IKNP-126','Ikan Kakap Merah','Lutjanidae Campechanus','Perairan pesisir','Animalia')
INSERT INTO HEWAN
VALUES('IKNP-017','Ikan Teri','Anchovies','Perairan pesisir','Animalia')
INSERT INTO HEWAN
VALUES('IKNT-109','Ikan Cakalang','Katsuwonus pelamis','Perairan tropik','Animalia')

INSERT INTO MIGAS
VALUES('MB','Minyak bumi','Bawah tanah','90%-97% alkana, sisanya sikloalkana, alkena, alkuna, dan senyawa aromatik.','4,2 miliar barel','$80 per barel')
INSERT INTO MIGAS
VALUES('GB','Gas bumi','Bawah tanah','80%-95% metana, 6%-15% etana, sisanya propana dan butana','62,4 miliar MMBtu','$27,5 per MMbtu')
INSERT INTO MIGAS
VALUES('CBM','Coal Bed Methane','Bawah tanah','80%-95% metana, sisanya etana, propana, butana, dan gas non-hidrokarbon batubara','453 miliar MMbtu','$41,2 per MMbtu')

INSERT LOGAM
VALUES('TBA','Tembaga','Dasar laut','Cu','15,08 miliar ton','$9418 per ton')
INSERT LOGAM
VALUES('KBT','Kobalt','Dasar laut','Co','3,8 miliar ton','$82000 per ton')
INSERT LOGAM
VALUES('NKL','Nikel','Dasar laut','Ni','7.1 miliar ton','$19650 per ton')
INSERT LOGAM
VALUES('SNG','Seng','Dasar laut','Zn','29,5 miliar ton','$2444 per ton')
INSERT LOGAM
VALUES('LTH','Lithium','Dasar laut','Li','19,3 miliar ton','$8700 per ton')

INSERT INTO MEMILIKI
VALUES('12019','PSTA-002')
INSERT INTO MEMILIKI
VALUES('12019','MNRA-001')
INSERT INTO MEMILIKI
VALUES('12019','PSTA-004')
INSERT INTO MEMILIKI
VALUES('12019','IKNP-126')
INSERT INTO MEMILIKI
VALUES('12019','IKNT-109')
INSERT INTO MEMILIKI
VALUES('12031','PSTA-001')
INSERT INTO MEMILIKI
VALUES('12031','PSTA-002')
INSERT INTO MEMILIKI
VALUES('12031','IKNP-312')
INSERT INTO MEMILIKI
VALUES('12031','IKNP-017')
INSERT INTO MEMILIKI
VALUES('12025','PSTA-003')
INSERT INTO MEMILIKI
VALUES('12025','PSTA-004')
INSERT INTO MEMILIKI
VALUES('12025','IKNP-312')
INSERT INTO MEMILIKI
VALUES('12025','IKNP-126')
INSERT INTO MEMILIKI
VALUES('12025','IKNT-109')
INSERT INTO MEMILIKI
VALUES('12005','PSTA-001')
INSERT INTO MEMILIKI
VALUES('12005','MNRA-001')
INSERT INTO MEMILIKI
VALUES('12005','PSTA-003')
INSERT INTO MEMILIKI
VALUES('12005','PSTA-004')
INSERT INTO MEMILIKI
VALUES('12005','IKNP-312')
INSERT INTO MEMILIKI
VALUES('12005','IKNP-238')
INSERT INTO MEMILIKI
VALUES('12005','IKNP-126')
INSERT INTO MEMILIKI
VALUES('12005','IKNP-017')
INSERT INTO MEMILIKI
VALUES('12005','IKNT-109')
INSERT INTO MEMILIKI
VALUES('12032','PSTA-002')
INSERT INTO MEMILIKI
VALUES('12032','IKNP-238')
INSERT INTO MEMILIKI
VALUES('12032','IKNT-109')
INSERT INTO MEMILIKI
VALUES('12010','PSTA-002')
INSERT INTO MEMILIKI
VALUES('12010','PSTA-003')
INSERT INTO MEMILIKI
VALUES('12010','PSTA-004')
INSERT INTO MEMILIKI
VALUES('12010','IKNP-312')
INSERT INTO MEMILIKI
VALUES('12010','IKNP-238')
INSERT INTO MEMILIKI
VALUES('12010','IKNP-017')
INSERT INTO MEMILIKI
VALUES('12011','PSTA-001')
INSERT INTO MEMILIKI
VALUES('12011','IKNP-312')
INSERT INTO MEMILIKI
VALUES('12011','IKNP-238')

INSERT INTO TERDAPAT
VALUES('12032','CBM')
INSERT INTO TERDAPAT
VALUES('12032','KBT')
INSERT INTO TERDAPAT
VALUES('12005','GB')
INSERT INTO TERDAPAT
VALUES('12005','TBA')
INSERT INTO TERDAPAT
VALUES('12010','GB')
INSERT INTO TERDAPAT
VALUES('12011','MB')
INSERT INTO TERDAPAT
VALUES('12019','MB')
INSERT INTO TERDAPAT
VALUES('12031','TBA')
INSERT INTO TERDAPAT
VALUES('12031','NKL')
INSERT INTO TERDAPAT
VALUES('12025','CBM')
INSERT INTO TERDAPAT
VALUES('12025','SNG')
INSERT INTO TERDAPAT
VALUES('12025','LTH')