USE COMPANY
GO

/* 1(a) */
CREATE TABLE ANGGARAN (
	PNUM bigint NOT NULL,
	ANGGARAN int,
	FOREIGN KEY (PNUM) REFERENCES PROJECT(PNUMBER)
);

/* 1(b) */
INSERT INTO ANGGARAN (PNUM, ANGGARAN)
SELECT PNO, SUM(HOURS*100000) FROM WORKS_ON GROUP BY PNO;

GO