USE COMPANY
GO

CREATE TRIGGER TGR_UPDT_ANGGARAN
ON WORKS_ON
AFTER UPDATE
AS
BEGIN
	UPDATE ANGGARAN 
	SET ANGGARAN = (SELECT SUM(W.HOURS*100000) FROM INSERTED AS W GROUP BY PNO)
	WHERE (SELECT W.PNO FROM INSERTED AS W) = ANGGARAN.PNUM
END

GO