USE COMPANY
GO

SELECT * 
FROM EMPLOYEE
WHERE CONVERT(nvarchar, ADDRESS) NOT IN (
	SELECT DLOCATION
	FROM DEPT_LOCATIONS)
AND SEX IN (
	SELECT SEX 
	FROM EMPLOYEE
	GROUP BY SEX
	HAVING COUNT(SEX) >= ALL (
		SELECT COUNT(SEX) 
		FROM EMPLOYEE
		GROUP BY SEX))
AND SSN IN (
	SELECT ESSN
	FROM WORKS_ON
	WHERE HOURS > (
		SELECT AVG(HOURS) 
		FROM WORKS_ON))
GO